---
seed: 3
c_stages:
    get_data: False
    test: True
c_data:
    cluster: False
    prefix: /nvme/scratch/ja952kire/temp_graph/data
    start_date: "2018_01_01"
    end_date: "2018_01_10"
    num_entities_per_article: 4
    database: "temp_graph.db"
    salience_threshold: 0.02
    limit:
c_model:
    prefix: models
    predict_horizon: 100
c_results:
    prefix: experiments
c_analyze:
    figures: reports/figures
