---
seed: 3 # random seed
c_stages:
    get_data: False
    train: True
c_data:
    cluster: False # indicates if preprocessing is executed on the cluster
    prefix: data/
    start_date: "2018_01_01" # GDELT data to pull from this date on
    end_date: "2019_01_01" # GDELT data until this date
    num_entities_per_article: 4
    database: "temp_graph.db"
    salience_threshold: 0.02 # cutoff value for a valid entity
    limit:
c_model:
    prefix: models
    predict_horizon: 200 # how many days to predict in the future
c_tgn:
    batch_size: 100
    n_degree: 10
    n_head: 2
    n_epoch: 10
    n_layer: 1
    lr: 3e-4
    patience: 5
    drop_out: 0.1
    node_dim: 100
    time_dim: 100
    backprop_every: 1
    use_memory:  True
    embedding_module: graph_attention
    message_function: identity
    aggregator: last
    memory_update_at_end: True
    message_dim: 100
    memory_dim: 100
    different_new_nodes: True
    uniform: True
    randomize_features: True
    use_destination_embedding_in_message: True
    use_source_embedding_in_message: True
    n_neg: 1
    use_validation: True
    new_node: True
c_results:
    prefix: experiments
c_analyze:
    figures: reports/figures
