version: 1
disable_existing_loggers: False
formatters:
    standard:
        format: '%(asctime)s [%(levelname)s] %(name)s: %(message)s'
root:
    handlers: [stream_handler]
    level: INFO
handlers:
    stream_handler:
        level: NOTSET
        formatter: standard
        class: logging.StreamHandler
        stream: ext://sys.stdout
    file_handler:
        level: INFO
        formatter: standard
        class: logging.FileHandler
        filename: general.log
    results:
        level: DEBUG
        formatter: standard
        class: logging.FileHandler
        filename: results.log
    analyze:
        level: INFO
        formatter: standard
        class: logging.FileHandler
        filename: analyze.log
    preprocess:
        level: INFO
        formatter: standard
        class: logging.FileHandler
        filename: preprocess.log
loggers:
    hids:
        handlers: [file_handler, stream_handler]
        level: DEBUG
        propagate: 0
    hids.results:
        handlers: [results, stream_handler]
        level: INFO
        propagate: 0
    hids.preprocess:
        handlers: [preprocess, stream_handler]
        level: INFO
        propagate: 0
    hids.analyze:
        handlers: [analyze, stream_handler]
        level: INFO
        propagate: 0
